### ISSUE TITLE
[Runtime Issue]: Mercenary game assets confusion

### ISSUE THREAD

**Issue by JeodC** [DescentDevelopers/Descent3#255]
### Build Version

current

### Operating System Environment

- [X] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [X] Mac OS X
- [X] Linux (specify distribution and version below)

### Description

The game will check for the existence of Mercenary expansion via registry string. If it doesn't exist, the Black Pyro ship is supposedly unable to be selected at Pilot->Configure (after passing Merc Level 2). #254 attempts to fix that, but Merc assets still failed to load from the steam version of the game where they are located in `extra.hog`.

Only after installing the CD-ROM, installing the Merc CD, then patching to 1.4, can the game function as expected by copying `merc.hog` and `EXTRA.HOG` (renamed to `extra.hog`) to the other install directory.

In essence #254 is only a partial fix. The underlying cause of this bug is unknown.

File breakdown:

`EXTRA.HOG` contains the following:
![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/867ad460-6d40-4d25-8b3e-114224e65d88)

`merc.hog` contains a lot more:
![image](https://github.com/DescentDevelopers/Descent3/assets/47716344/4dc2ca93-f205-41a7-bfd1-5189197ec29b)

In comparing the two, it appears the steam release `extra.hog` is a copy of `merc.hog`, and `EXTRA.HOG` from the CD is missing entirely.

**Comment by JeodC** [comment]
In the digital releases, `merc.hog` is renamed to `extra.hog`, and `EXTRA.HOG` is renamed to `extra1.hog`.

**Comment by Jayman2000** [comment]
> The underlying cause of this bug is unknown.

I actually think that this is intentional, and I think that I know the underlying cause. I believe that [this chunk of code](https://github.com/DescentDevelopers/Descent3/blob/d132a1c737450778b39c4d2c8962bb424c6a0b70/Descent3/init.cpp#L1696-L1724) is what causes the behavior, but I haven’t tested it yet.

> Only after installing the CD-ROM, installing the Merc CD, then patching to 1.4, can the game function as expected by copying `merc.hog` and `EXTRA.HOG` (renamed to `extra.hog`) to the other install directory.

Here’s the mechanics of how installing Descent 3: Mercenary via CD fixes the issue. The Descent 3: Mercenary CD has a file in its root directory named `AUTORUN.INF`. Here’s the contents of that file:

```ini
[autorun]
open=setup.exe -autorun
icon=Descent3AutoRun.ico
```

That `AUTORUN.INF` file will make it so that when the CD is inserted, older versions of Windows will automatically run `setup.exe -autorun`. If you run the installer without the `-autorun` option, then it won’t create the `…Uninstall\Descent3 Mercenary` registry key.

I believe that this is a crude form of DRM. If you were to download the files illegally from the Internet, then `AUTORUN.INF` probably won’t get used because you probably won’t bother putting the files onto a CD. If `AUTORUN.INF` doesn’t get used, then the `-autorun` parameter probably won’t get used which means that the `…Uninstall\Descent3 Mercenary` registry key won’t get created. If those registry keys don’t get created, then Descent 3 will refused to load some of Descent 3: Mecenary’s content.

**Comment by JeodC** [comment]
That is only part of the issue. See the latest commit in the PR. Still testing.
