### ISSUE TITLE
[Runtime Issue]: `-useexedir` causes game to crash instantly

### ISSUE THREAD

**Issue by Jayman2000** [DescentDevelopers/Descent3#322]
### Build Version

v1.5.0 7d38dde2

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [ ] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [X] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [X] Anarchy
- [X] Hyper-Anarchy
- [X] Robo-Anarchy
- [X] Team Anarchy
- [X] Capture the Flag
- [X] Bounty
- [X] Entropy
- [X] Hoard
- [X] Monsterball
- [X] Cooperative

### Game Environment

I’m running NixOS 23.11 and using game data from the Windows Dual-Jewel version of Descent 3 v1.4.

### Description

Whenever I try to run the game with `-useexedir`, it crashes with these errors:

```
Error: Unable to set temporary directory to: "./Descent3/custom/cache"

Error: Unable to set temporary directory to: "./Descent3/custom/cache"(Descent 3 Error)

System Error

Press OK to exit, CANCEL to ignore this error and continue.
SIGNAL 5 caught, aborting
DDIO: ddio_InternalClose() called.
DDIO: ddio_InternalClose() returning.
```

### Regression Status

I don’t know.

### Steps to Reproduce

1. Run `Descent3 -useexedir`.

**Comment by JeodC** [comment]
Does your exedir have those folders?

**Comment by JeodC** [comment]
The temp directories are not created by the game, they are assumed to already exist ([init.cpp](https://github.com/DescentDevelopers/Descent3/blob/1f94e623b24ef7bb5a1e4bc797842b2d806e70e3/Descent3/init.cpp#L2213C1-L2318C2)). Create `custom/cache` and it will work.

**Comment by Jayman2000** [comment]
> Does your exedir have those folders?

Yes, there are `cache/` and `custom/cache/` folders in the same folder as my `Descent3` executable.

> The temp directories are not created by the game, they are assumed to already exist ([init.cpp](https://github.com/DescentDevelopers/Descent3/blob/1f94e623b24ef7bb5a1e4bc797842b2d806e70e3/Descent3/init.cpp#L2213C1-L2318C2)). Create `custom/cache` and it will work.

Unfortunately, the game still crashes when I run it like this:

```bash
mkdir -p cache custom/cache && ./Descent3 -useexedir
```

I want to emphasize that the game does not crash when I run it without `-useexedir`.

**Comment by JeodC** [comment]
Ah, I think I see the problem. In [init.cpp](https://github.com/DescentDevelopers/Descent3/blob/1f94e623b24ef7bb5a1e4bc797842b2d806e70e3/Descent3/init.cpp#L1565) where `-exedir` is processed:
```cpp
// Set the base directory
  int dirarg = FindArg("-setdir");
  int exedirarg = FindArg("-useexedir");
  if (dirarg) {
    strcpy(Base_directory, GameArgs[dirarg + 1]);
  } else if (exedirarg) {
    strcpy(Base_directory, GameArgs[0]);
    int len = strlen(Base_directory);
    for (int i = (len - 1); i >= 0; i--) {
      if (i == '\\') {
        Base_directory[i] = '\0';
      }
    }
    mprintf((0, "Using working directory of %s\n", Base_directory));
  } else {
    ddio_GetWorkingDir(Base_directory, sizeof(Base_directory));
  }
  ```
I believe the `if (i == '\\')` should be `if (Base_directory[i] == '\\')`. The code is supposed to truncate the executable from the path, so if your path is `C:\Games\Descent3.exe`, it truncates to `C:\Games\`. The loop intends to traverse the `Base_directory` string backwards until it gets to the first `\`. But this appears to be comparing the index itself, rather than the character value. It's comparing a number to a character.

**Comment by JeodC** [comment]
Please try the artifact from #324 and confirm if it works for you.

**Comment by Jayman2000** [comment]
> Please try the artifact from #324 and confirm if it works for you.

I tried building that PR from source, and it did not fix the issue.

**Comment by JeodC** [comment]
> > Please try the artifact from #324 and confirm if it works for you.
> 
> I tried building that PR from source, and it did not fix the issue.

Please try again--I added an `OR` check for forward slashes, for unix systems.

**Comment by Jayman2000** [comment]
> Please try again--I added an `OR` check for forward slashes, for unix systems.

I tried the new version of your PR. When I run `./Descent3 -useexedir` it gives me this error:

```
Error: Unable to set temporary directory to: "./custom/cache"

Error: Unable to set temporary directory to: "./custom/cache"(Descent 3 Error)
```

When I run `<full-path-to-exe-dir>/Descent3 -useexedir`, it gives me a slightly different error:

```
Error: Unable to set temporary directory to: "/custom/cache"

Error: Unable to set temporary directory to: "/custom/cache"(Descent 3 Error)
```

**Comment by JeodC** [comment]
I examined the code process and it should work--I've modified a few of the [error messages](https://github.com/DescentDevelopers/Descent3/pull/324/files) to clarify what step the game fails at.

**Comment by JeodC** [comment]
@Lgt2x am I missing anything here? To me it looks like it comes down to two possibilities: permissions or unix interpreting `custom/cache` as a filepath and not a directory path.

**Comment by Lgt2x** [comment]
So #324 (now fixed with a break) only works when the game is launched using an absolute path (ie `~/Descent3/Descent3 -useexedir`) but not when using a relative path (`./Descent3/Descent3 -useexedir`). That is, because `argv[0]` in a program is not necessarily an absolute path, but is used as one in this situation (see [here](https://stackoverflow.com/questions/933850/how-do-i-find-the-location-of-the-executable-in-c) for possible mitigation).

I think we can proceed with #324 (needs Windows testing) but leave this issue open until we implement a better solution to get the running executable's absolute path.
